// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {deeplink} from '../models';

export function ConsumePendingDeepLink():Promise<types.DeepLinkResponse>;

export function GetCurrentVersion():Promise<types.AppVersionResponse>;

export function GetGameVersion():Promise<types.GameVersionResponse>;

export function GetPlatform():Promise<types.PlatformResponse>;

export function GetTotalMemory():Promise<number>;

export function HandleDeepLinkTarget(arg1:deeplink.Target):Promise<void>;

export function HandleDeepLinkURL(arg1:string):Promise<void>;

export function InstallLinuxSandbox():Promise<types.GenericResponse>;

export function IsGameRunning():Promise<types.GameRunningResponse>;

export function IsStartupReady():Promise<types.StartupReadyResponse>;

export function LaunchGame(arg1:boolean):Promise<types.GenericResponse>;

export function ManuallyCheckForUpdates():Promise<types.GenericResponse>;

export function OpenImportAssetDialog(arg1:types.AssetType):Promise<types.ImportAssetDialogResponse>;

export function OpenInFileExplorer(arg1:string):Promise<types.GenericResponse>;

export function SandboxIsInstalled():Promise<types.SandboxStatusResponse>;

export function StopGame():Promise<types.GenericResponse>;

export function ValidateImportedMapArchives(arg1:Array<string>):Promise<types.ImportValidationResponse>;
