// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {semver} from '../models';

export function CancelInstall(arg1:types.AssetType,arg2:string):Promise<types.AssetUninstallResponse>;

export function ComputeDependencyList(arg1:string,arg2:types.VersionInfo):Promise<types.DependencyListResponse>;

export function DetectedGameVersion():Promise<semver.Version|boolean>;

export function FindMapCodeConflict(arg1:string,arg2:string,arg3:boolean):Promise<types.MapCodeConflict|boolean>;

export function ImportAsset(arg1:types.AssetType,arg2:string,arg3:boolean):Promise<types.AssetInstallResponse>;

export function InstallAsset(arg1:types.InstallAssetRequest):Promise<types.AssetInstallResponse>;

export function UninstallAsset(arg1:types.AssetType,arg2:string):Promise<types.AssetUninstallResponse>;

export function ValidateImportedMapArchive(arg1:string):Promise<types.ImportArchiveValidation>;
