// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelInstall(arg1, arg2) {
  return window['go']['downloader']['Downloader']['CancelInstall'](arg1, arg2);
}

export function ComputeDependencyList(arg1, arg2) {
  return window['go']['downloader']['Downloader']['ComputeDependencyList'](arg1, arg2);
}

export function DetectedGameVersion() {
  return window['go']['downloader']['Downloader']['DetectedGameVersion']();
}

export function FindMapCodeConflict(arg1, arg2, arg3) {
  return window['go']['downloader']['Downloader']['FindMapCodeConflict'](arg1, arg2, arg3);
}

export function ImportAsset(arg1, arg2, arg3) {
  return window['go']['downloader']['Downloader']['ImportAsset'](arg1, arg2, arg3);
}

export function InstallAsset(arg1) {
  return window['go']['downloader']['Downloader']['InstallAsset'](arg1);
}

export function UninstallAsset(arg1, arg2) {
  return window['go']['downloader']['Downloader']['UninstallAsset'](arg1, arg2);
}

export function ValidateImportedMapArchive(arg1) {
  return window['go']['downloader']['Downloader']['ValidateImportedMapArchive'](arg1);
}
